config/routes.rb
class AudioRoutingConcern
  def matches?(request)
    query = [
      ActiveFedora::SolrQueryBuilder.raw_query(ActiveFedora.id_field, request.params[:id]),
      ActiveFedora::SolrQueryBuilder.construct_query_for_rel(has_model: AudioRecording.to_class_uri)]
        .join(' AND '.freeze)
    results = ActiveFedora::SolrService.query query, fl: 'has_model_ssim'
    results.present?
  end
end

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  root 'welcome#index'

  get 'welcome/about', as: 'about'

  post 'contact_us' => 'contact_us#create', as: :contact_us
  get 'contact_us' => 'contact_us#new', as: :contact_us_form

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get 'lib/:prot/:shoulder/:id' => 'curation_concerns/audio_recordings#show', constraints: AudioRoutingConcern.new
  get 'lib/:prot/:shoulder/:id' => 'catalog#show'

  resources :local_authorities, only: :index

  get 'authorities/agents/:id',        to: 'local_authorities#show', as: 'agent'
  get 'authorities/people/:id',        to: 'local_authorities#show', as: 'person'
  get 'authorities/groups/:id',        to: 'local_authorities#show', as: 'group'
  get 'authorities/organizations/:id', to: 'local_authorities#show', as: 'organization'
  get 'authorities/topics/:id',        to: 'local_authorities#show', as: 'topic'

  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'
  mount Riiif::Engine => '/images'
  mount Qa::Engine => '/qa'
  mount HydraEditor::Engine => '/'
  mount Hydra::Collections::Engine => '/'

  mount CurationConcerns::Engine, at: '/'
  curation_concerns_collections
  curation_concerns_basic_routes do
    resource :access, only: [:edit, :update, :destroy], controller: 'access'
    concerns :exportable
  end
  curation_concerns_embargo_management

  resources :records, only: :destroy do
    get 'new_merge', on: :member
    post 'merge', on: :member
  end
end

app/controllers/contact_us_controller.rb
# Sends email to the admin from the contact form
class ContactUsController < ApplicationController
  # Display the "Contact Us" form the the user.
  def new
  end

  # When a user submits the "Contact Us" form, send the email.
  def create
    from = %("#{params[:name]}" <#{params[:email]}>)
    spam = !params[:zipcode].blank?
    email = ContactUsMailer.web_inquiry(from, params[:category], params[:message], spam)
    email.deliver_now

    flash[:notice] = 'Thank you for the feedback.  Your submission has been successfully sent to the ADRL.'
    redirect_to :back
  end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
  def contact_us_categories
    ['General Inquiry or Request', 'Feedback', 'Report Problem']
  end

  def contact_us_fields_class
    'col-xs-12 col-sm-6'
  end
end

app/views/contact_us/new.html.erb
<div id="contact-us-page">
  <div class='row'>
    <h1> Contact Us </h1>
    <p> Please use the contact form to submit general questions about the Alexandria Digital Research Library website, to report a problem you are experiencing with the system, or to provide feedback. </p>
  </div>

  <%= form_tag(contact_us_form_path) do %>
    <div class='row'>
      <%= label_tag :category, 'Issue Type (Please Select)' %>
      <br />
      <%= select_tag :category, options_for_select(contact_us_categories, 'General Inquiry or Request'), required: 'required' %>
    </div>

    <div class='row'>
      <%= label_tag :name, 'Your Name' %>
      <br />
      <%= text_field_tag :name, nil, required: 'required', class: contact_us_fields_class %>
    </div>

    <div class='row'>
      <%= label_tag :email, 'Your Email' %>
      <br />
      <%= email_field_tag :email, nil, required: 'required', class: contact_us_fields_class %>
    </div>

    <div class='row invisible'>
      <%= label_tag :zipcode, 'Your Zip Code (Humans: Leave This Empty)' %>
      <br />
      <%= text_field_tag :zipcode, nil, class: contact_us_fields_class %>
    </div>

    <div class='row'>
      <%= label_tag :message %>
      <br />
      <%= text_area_tag :message, nil, rows: 8, required: 'required', class: contact_us_fields_class %>
    </div>

    <div class='form-actions row'>
      <%= submit_tag('Send', class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>