config/routes.rb
class AudioRoutingConcern
  def matches?(request)
    query = [
      ActiveFedora::SolrQueryBuilder.raw_query(ActiveFedora.id_field, request.params[:id]),
      ActiveFedora::SolrQueryBuilder.construct_query_for_rel(has_model: AudioRecording.to_class_uri)]
        .join(' AND '.freeze)
    results = ActiveFedora::SolrService.query query, fl: 'has_model_ssim'
    results.present?
  end
end

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  root 'welcome#index'

  get 'welcome/about', as: 'about'

  post 'contact_us' => 'contact_us#create', as: :contact_us
  get 'contact_us' => 'contact_us#new', as: :contact_us_form

  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get 'lib/:prot/:shoulder/:id' => 'curation_concerns/audio_recordings#show', constraints: AudioRoutingConcern.new
  get 'lib/:prot/:shoulder/:id' => 'catalog#show'

  resources :local_authorities, only: :index

  get 'authorities/agents/:id',        to: 'local_authorities#show', as: 'agent'
  get 'authorities/people/:id',        to: 'local_authorities#show', as: 'person'
  get 'authorities/groups/:id',        to: 'local_authorities#show', as: 'group'
  get 'authorities/organizations/:id', to: 'local_authorities#show', as: 'organization'
  get 'authorities/topics/:id',        to: 'local_authorities#show', as: 'topic'

  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'
  mount Riiif::Engine => '/images'
  mount Qa::Engine => '/qa'
  mount HydraEditor::Engine => '/'
  mount Hydra::Collections::Engine => '/'

  mount CurationConcerns::Engine, at: '/'
  curation_concerns_collections
  curation_concerns_basic_routes do
    resource :access, only: [:edit, :update, :destroy], controller: 'access'
    concerns :exportable
  end
  curation_concerns_embargo_management

  resources :records, only: :destroy do
    get 'new_merge', on: :member
    post 'merge', on: :member
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  include CurationConcerns::CatalogController
  include BlacklightRangeLimit::ControllerOverride
  # helper Openseadragon::OpenseadragonHelper

  self.theme = 'alexandria'

  rescue_from Blacklight::Exceptions::RecordNotFound do |e|
    logger.error "(Blacklight::Exceptions::RecordNotFound): #{e.inspect}"
    @unknown_type = 'Document'
    @unknown_id = params[:id]
    render 'errors/not_found', status: 404
  end

  # enforce_show_permissions is from hydra-access-controls gem
  before_filter :enforce_show_permissions, only: :show

  def enforce_show_permissions(_opts = {})
    permissions = current_ability.permissions_doc(params[:id])
    return if can?(:discover, permissions)

    raise Hydra::AccessDenied.new(
      'You do not have sufficient access privileges to access this document.',
      :discover, params[:id])
  end

  # Turn off SMS
  # https://groups.google.com/d/msg/blacklight-development/l_zHRF_GQc8/_qUUbJSs__YJ
  CatalogController.blacklight_config.show.document_actions.delete(:sms)

  add_show_tools_partial(:edit, partial: 'catalog/edit', if: :editor?)
  add_show_tools_partial(:download, partial: 'catalog/download')
  add_show_tools_partial(:access, partial: 'catalog/access', if: :show_embargos_link?)

  configure_blacklight do |config|
    config.search_builder_class = SearchBuilder
    config.view.gallery.partials = [:index_header, :index]
    config.view.slideshow.partials = [:index]
    config.add_nav_action(:admin_menu, partial: 'shared/admin_menu', if: :admin_menu?, class: 'dropdown')

    # config.show.tile_source_field = :content_metadata_image_iiif_info_ssm
    # config.show.partials.insert(1, :openseadragon)

    config.default_solr_params = {
      qf: 'title_tesim lc_subject_label_tesim accession_number_tesim keywords_tesim author_tesim',
      wt: 'json',
      qt: 'search',
      rows: 10,
    }

    # solr field configuration for search results/index views
    config.index.title_field = solr_name('title', :stored_searchable)
    config.index.display_type_field = 'has_model_ssim'
    config.index.thumbnail_field = ObjectIndexer.thumbnail_field

    config.show.partials = [:media, :show]

    # Solr fields that will be treated as facets by the blacklight application
    #
    # The ordering of the field names is the order of the display.
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    #
    # * If left unset, then all facet values returned by solr will be
    #   displayed (not always all results in Fedora; see
    #   https://github.library.ucsb.edu/ADRL/alexandria/issues/13)
    #
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    #   solr request, with actual solr request being +1 your configured limit --
    #   you configure the number of items you actually want _tsimed_ in a page.
    #
    # * If set to 'true', then no additional parameters will be sent
    #   to solr, but any 'sniffed' request limit parameters will be
    #   used for paging, with paging at requested limit -1. Can sniff
    #   from facet.limit or f.specific_field.facet.limit solr request
    #   params. This 'true' config can be used if you set limits in
    #   :default_solr_params, or as defaults on the solr side in the
    #   request handler itself. Request handler defaults sniffing
    #   requires solr requests to be made with "echoParams=all", for
    #   app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field solr_name('work_type_label', :facetable), label: 'Type of Resource', limit: true
    config.add_facet_field solr_name('location_label', :facetable), label: 'Location', limit: true
    config.add_facet_field ContributorIndexer::FACETABLE_CONTRIBUTOR, label: 'Contributor', limit: true
    config.add_facet_field solr_name('lc_subject_label', :facetable), label: 'Subject', limit: 20
    config.add_facet_field solr_name('publisher', :facetable), label: 'Publisher', limit: true
    config.add_facet_field ObjectIndexer::FACETABLE_YEAR, label: 'Year', range: true
    config.add_facet_field solr_name('form_of_work_label', :facetable), label: 'Type', limit: true
    config.add_facet_field solr_name('collection_label', :symbol), label: 'Collection', limit: true
    config.add_facet_field solr_name('department', :facetable), label: 'Department', limit: true

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!
    # use this instead if you don't want to query facets marked :show=>false
    # config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field solr_name('lc_subject_label', :stored_searchable), label: 'Subject'
    config.add_index_field ContributorIndexer::CONTRIBUTOR_LABEL, label: 'Creators / Contributors'
    config.add_index_field solr_name('publisher', :stored_searchable), label: 'Publisher'
    config.add_index_field solr_name('author', :stored_searchable), label: 'Author'
    config.add_index_field 'published_ss', label: 'Published'
    config.add_index_field 'date_created_ss', label: 'Date Created'
    config.add_index_field solr_name('form_of_work_label', :stored_searchable), label: 'Type'
    config.add_index_field solr_name('location_label', :stored_searchable), label: 'Location'
    config.add_index_field solr_name('language', :stored_searchable), label: 'Language'

    Metadata::RELATIONS.each do |key, _value|
      config.add_show_field solr_name("#{key}_label", :stored_searchable), label: key.to_s.titleize
    end

    config.add_show_field 'isbn_ssim', label: 'ISBN'
    config.add_show_field solr_name('accession_number', :symbol), label: 'Accession Number'
    config.add_show_field solr_name('alternative', :stored_searchable), label: 'Alternative Title'
    config.add_show_field solr_name('collection_label', :symbol), label: 'Collection', helper_method: :link_to_collection
    config.add_show_field solr_name('copyright_status_label', :stored_searchable), label: 'Copyright Status'
    config.add_show_field solr_name('created', :displayable), label: 'Creation Date'
    config.add_show_field solr_name('date_copyrighted', :displayable), label: 'Copyright Date'
    config.add_show_field solr_name('date_other', :displayable), label: 'Other Dates'
    config.add_show_field solr_name('date_valid', :displayable), label: 'Valid Dates'
    config.add_show_field solr_name('description', :stored_searchable), label: 'Description', separator: '<br><br>'.html_safe
    config.add_show_field solr_name('digital_origin', :stored_searchable), label: 'Digital Origin'
    config.add_show_field solr_name('extent', :displayable), label: 'Extent'
    config.add_show_field solr_name('form_of_work_label', :stored_searchable), label: 'Genre(s)', separator: '; '
    config.add_show_field solr_name('identifier', :displayable), label: 'ARK'
    config.add_show_field solr_name('institution_label', :stored_searchable), label: 'Contributing Institution'
    config.add_show_field solr_name('issued', :displayable), label: 'Issued Date'
    config.add_show_field solr_name('latitude', :displayable, type: :string), label: 'Latitude'
    config.add_show_field solr_name('lc_subject_label', :stored_searchable), label: 'Subject'
    config.add_show_field solr_name('license_label', :stored_searchable), label: 'License'
    config.add_show_field solr_name('location_label', :stored_searchable), label: 'Location'
    config.add_show_field solr_name('longitude', :displayable, type: :string), label: 'Longitude'
    config.add_show_field solr_name('note_label', :stored_searchable), label: 'Notes', helper_method: :display_notes
    config.add_show_field solr_name('place_of_publication', :stored_searchable), label: 'Place of Publication'
    config.add_show_field solr_name('publisher', :stored_searchable), label: 'Publisher'
    config.add_show_field solr_name('rights_holder_label', :stored_searchable), label: 'Copyright Holder'
    config.add_show_field solr_name('series_name', :displayable), label: 'Series'
    config.add_show_field solr_name('sub_location', :displayable, type: :string), label: I18n.t('simple_form.labels.image.sub_location')
    config.add_show_field solr_name('system_number', :symbol), label: 'System Number'
    config.add_show_field solr_name('restrictions', :stored_searchable), label: 'Restrictions'
    config.add_show_field solr_name('work_type_label', :stored_searchable), label: 'Type of Resource'
    config.add_show_field solr_name('finding_aid', :stored_searchable), label: 'Finding Aid'

    config.add_show_field solr_name('degree_grantor', :symbol), label: 'Degree Grantor'
    config.add_show_field solr_name('marc_subjects', :stored_searchable), label: 'Subjects'
    config.add_show_field solr_name('keywords', :stored_searchable), label: 'Keywords'
    config.add_show_field solr_name('copyright', :displayable), label: 'Copyright'
    config.add_show_field solr_name('dissertation', :displayable), label: 'Dissertation'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,

app/views/catalog/_access_denied.html.erb
  <table class="table table-bordered" id="downloads">
    <tbody>
      <tr>
        <td class="access-row denied" colspan="2">Access: <%= t(".#{document.admin_policy_id}") %></td>
      </tr>
    </tbody>
  </table>

app/views/catalog/_delete.html.erb
<%= link_to "Delete this Record", record_path(document), data: { method: :delete, confirm: 'Are you sure you want to permanently delete this record?' } %>

app/views/catalog/_document.html.erb
<li id="document_<%= document.to_param %>" class="<%= render_document_class document %>" itemscope itemtype="<%= document.itemtype %>">
  <%= render_document_partials document, blacklight_config.view_config(document_index_view_type).partials, document_counter: document_counter %>
</li>

app/views/catalog/_download.html.erb
<%= link_to 'Download Metadata', solr_document_path(document, format: :ttl) %>

app/views/catalog/_edit.html.erb
<%= link_to "Edit Metadata", hydra_editor.edit_record_path(document) %>

app/views/catalog/_home_text.html.erb
Enter one or more words into the search box above to search the bibliographic records of all items in the Alexandria Digital Research Library, or the facets at left to browse the collections. Some materials in ADRL are subject to copyright and other access restrictions. Therefore, not all materials are made available to the public.

app/views/catalog/_index_header_default.html.erb
_index_header_list_default.html.erb

app/views/catalog/_index_slideshow.html.erb
<% # we're overriding this view just to use an image url that is not he default thumbnail url %>
<div class="item<%= ' active' if document_counter == 0 %>">
  <div class="frame">
      <%= image_tag document.first('image_url_ssm') %>
      <div class="caption">
        <%= render_index_field_value document, document_show_link_field(document) %>
      </div>
      <span class="counter">
        <%= t :'blacklight_gallery.catalog.modal_slideshow.counter', counter: document_counter + 1, count: count %>
      </span>
  </div>
</div>

app/views/catalog/_media_etd.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render 'show_header_default', document: document %>
  </div>
</div>

app/views/catalog/_media_image.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="stage-wrapper clearfix">
      <div class="stage clearfix">
        <div class="stage-container">
          <div class="jcarousel-wrapper">
            <div class="jcarousel">
              <ul class="clearfix">
                <%=
                r = ''
                Array(document['image_url_ssm']).each do |img|
                  r << '<li>'
                  r << image_tag(img, style: 'width: 100%')
                  r << '</li>'
                end
                r.html_safe
                %>
              </ul>
            </div>

            <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
            <a href="#" class="jcarousel-control-next">&rsaquo;</a>

            <p class="jcarousel-pagination"></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <%= render 'show_header_default', document: document %>
  </div>
</div>

app/views/catalog/_merge_link.html.erb
<%= link_to "Merge this Record", new_merge_record_path(document) %>

app/views/catalog/_show_image.html.erb
<dl class="dl-horizontal  dl-invert">
  <% document_show_fields(document).each do |solr_fname, field| -%>
    <% if should_render_show_field? document, field %>
	    <dt class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_label document, :field => solr_fname %></dt>
	    <dd class="blacklight-<%= solr_fname.parameterize %>"><%= render_document_show_field_value document, :field => solr_fname %></dd>
    <% end -%>
  <% end -%>
</dl>

app/views/catalog/facet.html.erb
<div class="facet_pagination top">
  <%= render :partial=>'facet_pagination' %>
</div>

<div class="modal-header">
  <button type="button" class="ajax-modal-close close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 class="modal-title"><%= 'Browse by ' unless request.xhr? %><%= facet_field_label(@facet.key) %></h3>
</div>
<div class="modal-body">
  <div class="facet_extended_list">
  <%= render_facet_limit(@display_facet, layout: false) %>
  </div>
</div>

<div class="modal-footer">

  <div class="facet_pagination bottom">
    <%= render :partial=>'facet_pagination' %>
  </div>
</div>

app/views/catalog/index.html.erb
<%# This partial is overriden so the navbar partial won't be drawn %>
<% provide :page_title, "#{application_name} Search Results" %>
<% provide :page_class, 'search' %>

<% provide :sidebar do %>
  <%= render 'search_sidebar' %>
<% end %>

<div id="content">
  <%= render 'search_results' %>
</div>